# ~/.config/starship.toml

# Inserts a blank line between shell prompts
add_newline = true

# Change the default prompt format
format = """\
[╭╴](238)$os\
$all[╰─](238)$character"""

# Change the default prompt characters
[character]
success_symbol = '[](238)'
error_symbol = '[](238)'

# ---

[os]
format ='[$symbol](bold blue)'   
disabled = false

[os.symbols]
Windows = ' '
Arch = '󰣇'
Ubuntu = ' '

# ---

# Shows the username
[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user]($style) '
disabled = true  # disable in powershell
show_always = false

# Shows current directory
[directory]
truncation_length = 1
# truncation_symbol = '…/'
home_symbol = '󰋞 ~'
read_only_style = '197'
read_only = '  '
format = 'at [$path]($style)[$read_only]($read_only_style) '

# Shows current git branch
[git_branch]
symbol = '󰊢 '
format = 'on [$symbol$branch]($style) '
# truncation_length = 4
truncation_symbol = '…/'
style = 'bold green'

# Shows current git
[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = 'bold green'
conflicted = '🏳'
up_to_date = ' '
untracked = ' '
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
stashed = '󰏗 '
modified = ' '
staged = '[++\($count\)](green)'
renamed = '󰖷 '
deleted = ' '

# Shows kubernetes context and namespace
[kubernetes]
format = 'via [󱃾 $context\($namespace\)](bold purple) '
disabled = false

# ---

[terraform]
format = 'via [ terraform $version]($style) 壟 [$workspace]($style) '

[vagrant]
format = 'via [ vagrant $version]($style) '

[docker_context]
format = 'via [ $context](bold blue) '

[helm]
format = 'via [ $version](bold purple) '

[python]
symbol = '󰌠 '
python_binary = 'python3'

[nodejs]
format = 'via [󰎙 $version](bold green) '

[ruby]
format = 'via [ $version]($style) '