[tools]
python = "latest"
node = "latest"
bun = "latest"
deno = "latest"
rust = "latest"
go = "latest"
uv = "latest"
act = "latest"
ruff = "latest"
biome = "latest"

[settings]
python.uv_venv_auto = true
experimental = true
