[tools]
python = "latest"
node = "latest"
bun = "latest"
deno = "latest"
rust = "latest"
go = "latest"
act = "latest"
hcloud = "latest"
bundler = "latest"
ruby = "latest"
uv = "latest"

[settings]
python.uv_venv_auto = true
