[tools]
usage = "latest"
python = "latest"
node = "latest"
bun = "latest"
deno = "latest"
go = "latest"
uv = "latest"
act = "latest"

[settings]
python.uv_venv_auto = true
experimental = true
idiomatic_version_file_enable_tools = ["python"]
