#:tombi schema.strict = false

[tools]
# Internals
watchexec = "latest" 

# Languages & runtimes
bun = "latest"
deno = "latest"
go = "latest"
node = "latest"
python = "latest"
rust = "latest"

# Package managers
ni = "latest"
nub = "latest"
pipx = "latest"
pnpm = "latest"
uv = "latest"

# CLI tools
atuin = "latest"
aube = "latest"
bat = "latest"
dust = "latest"
gdu = "latest"
gh = "latest"
topgrade = "latest"
viteplus = "latest"
"aqua:protonpass/pass-cli" = "latest"

# GitHub Actions
act = "latest"
actionlint = "latest"
pinact = "latest"
zizmor = "latest"

# AI tools
claude = "latest"
codex = "latest"
opencode = "latest"
pi = "latest"

[settings]
auto_install = true
auto_update = true
idiomatic_version_file_enable_tools = ["python", "node"]
trusted_config_paths = ["~/i"]

[settings.python]
uv_venv_auto = "create|source"
compile = false
